package com.example.demo.entity;

public class StudentEntity{
    wvwhwwgwgslsgwoiosuhsvvovoggioojg0ijovjsdbv9u9ghuonnlnljbinvvjkkjijpvhugrjjpsoivvklskjihhhkviioonvvosiihnnpijiihnnjnvsigriihgeehhgubbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdbbbbbbbbbbbbbbbbbbbbbbbbb
}